# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Task
pod 'SwiftMessages'
pod 'Toast-Swift', '~> 5.0.0'
pod 'Alamofire', '~> 4.7'
pod 'IQKeyboardManagerSwift'
pod 'MBProgressHUD'
pod 'IBAnimatable'
pod 'Moya'
pod 'Kingfisher'
pod 'ZLSwipeableViewSwift'
pod 'UIColor+FlatColors'
pod 'Cartography'

end
